sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  s3:
    accessKeyId: AKIAZG5ZU7666MI7JRHE
    accessKeySecret: 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
    bucketName: elasticbeanstalk-us-east-2-633360154557
    endpoint: s3.us-east-2.amazonaws.com
